# Generated by Django 3.2.7 on 2021-10-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20211015_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='nama',
            field=models.CharField(max_length=30),
        ),
    ]
