# Generated by Django 3.2.8 on 2021-10-24 18:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('proposal', models.FileField(null=True, upload_to='uploads/company_photos/%Y/%m/')),
                ('nama_merek', models.CharField(max_length=30, verbose_name='Nama merek')),
                ('nama_perusahaan', models.CharField(max_length=35, verbose_name='Nama perusahaan')),
                ('alamat', models.CharField(default='', max_length=140, verbose_name='Alamat')),
                ('deskripsi', models.TextField(default='', max_length=3000, verbose_name='Deskripsi')),
                ('jumlah_lembar', models.BigIntegerField(verbose_name='Jumlah lembar saham')),
                ('nilai_lembar_saham', models.BigIntegerField(verbose_name='Nilai lembar saham')),
                ('kode_saham', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Must be upper case letters of 4 characters', regex='^[A-Z]{4}$')], verbose_name='Kode saham')),
                ('dividen', models.IntegerField(verbose_name='Dividen')),
                ('start_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('end_date', models.DateField(verbose_name='Batas waktu')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=24, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Must consists only lowercase alphanumeric and underscore characters', regex='^[a-z0-9_]+$')])),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('photo_profile', models.ImageField(null=True, upload_to='uploads/user_profile/%Y/%m/')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('foto_ktp', models.ImageField(null=True, upload_to='uploads/foto_ktp/%Y/%m/')),
                ('selfie_ktp', models.ImageField(null=True, upload_to='uploads/selfie_ktp/%Y/%m/')),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_lembar_saham', models.BigIntegerField()),
                ('tanggal_ditanam', models.DateField(auto_now_add=True)),
                ('tanggal_berakhir', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.company')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.investoraccount')),
            ],
        ),
        migrations.AddField(
            model_name='investoraccount',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.useraccount'),
        ),
        migrations.CreateModel(
            name='EntrepreneurAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPhoto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='uploads/company_photos/%Y/%m/')),
                ('img_index', models.IntegerField()),
                ('alt', models.CharField(blank=True, default='', max_length=50)),
                ('caption', models.CharField(blank=True, default='', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='pemilik_usaha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.entrepreneuraccount'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=500)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.useraccount')),
                ('post_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.company')),
            ],
        ),
    ]
