# Generated by Django 3.2.8 on 2021-10-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='proposal',
            field=models.FileField(null=True, upload_to='uploads/company_photos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='foto_ktp',
            field=models.ImageField(null=True, upload_to='uploads/foto_ktp/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='selfie_ktp',
            field=models.ImageField(null=True, upload_to='uploads/selfie_ktp/%Y/%m/'),
        ),
    ]
