# Generated by Django 3.2.8 on 2021-10-24 05:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20211022_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='kode_saham',
            field=models.CharField(default='ABCD', max_length=4, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 4', regex='^[A-Z]{4}$')]),
            preserve_default=False,
        ),
    ]
