# Generated by Django 3.2.8 on 2021-10-24 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_company_kode_saham'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='alamat',
            field=models.CharField(default='', max_length=140, verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='company',
            name='kode_saham',
            field=models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 4', regex='^[A-Z]{4}$')], verbose_name='Kode saham'),
        ),
    ]
