variables:
  HEROKU_APIKEY: fb49a507-a3da-47a0-a661-386f0492a855
  HEROKU_APPNAME: bizzvest
  HEROKU_APP_HOST: bizzvest.herokuapp.com

stages:
  - deploy

Deployment:
  image: ruby:2.4
  stage: deploy
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider=heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_APIKEY
    - export HEROKU_API_KEY=$HEROKU_APIKEY
  environment:
    name: production
    url: $HEROKU_APP_HOST
  only:
    - master